version: "3.7"

volumes:
  local_postgres_data: {}


services:
  postgres:
    container_name: 'postgres-develops'
    image: postgres:13-alpine
    networks:
      - common
    env_file:
      - .postgres
    volumes:
    - local_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - common

  django:
    restart: on-failure
    container_name: 'django-develops'
    build: .
    depends_on:
      - postgres
    ports:
    - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - common

  celery:
    container_name: 'celery'
    build: .
    command: celery -A conf worker -B -l info
    depends_on:
      - postgres
      - redis
      - django
    networks:
      - common


networks:
  common:
    name: common
